---Question 1
SELECT E.LAST_NAME||', '||E.FIRST_NAME "Employee Name", M.LAST_NAME||', '||M.FIRST_NAME "Manager name", M.SALARY "Manager Salary", J.GRADE_LEVEL "Salary Grade"
FROM EMPLOYEES E JOIN EMPLOYEES M ON(E.MANAGER_ID=M.EMPLOYEE_ID) 
    JOIN JOB_GRADES J ON (M.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL)
WHERE M.SALARY> 12000;

---Question 2
SELECT E.FIRST_NAME||' '||E.LAST_NAME||' has worked in '||D.DEPARTMENT_NAME||' Department for '|| ROUND(MONTHS_BETWEEN(SYSDATE,E.HIRE_DATE),0)||' months.' "Employee Tenure"
FROM EMPLOYEES E JOIN DEPARTMENTS D USING(DEPARTMENT_ID);

---Question 3
SELECT D.DEPARTMENT_NAME "Department", MAX(E.SALARY)-MIN(E.SALARY) "Salary Difference"
FROM EMPLOYEES E JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;

---Question 4
SELECT M.EMPLOYEE_ID "Manager number", MIN(E.SALARY) "Lowest salary"
FROM EMPLOYEES E JOIN EMPLOYEES M ON(E.MANAGER_ID=M.EMPLOYEE_ID)
WHERE M.EMPLOYEE_ID IS NOT NULL
GROUP BY M.EMPLOYEE_ID
HAVING MIN(E.SALARY)> 5000
ORDER BY 2 DESC;

---Question 5
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID=(SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE FIRST_NAME='Kevin' AND LAST_NAME='Mourgos');

---Question 6
SELECT DEPARTMENT_ID "Department Number", MIN(SALARY) "Lowest salary"
FROM EMPLOYEES
HAVING AVG(SALARY)= (SELECT MAX(AVG(SALARY))FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
GROUP BY DEPARTMENT_ID;

---Question 7
select DEPARTMENT_NAME "Dept. with no sales Rep",
LOCATIONS.STREET_ADDRESS ||', '|| city ||','|| STATE_PROVINCE ||','|| country_id  "Location"
from JOB_HISTORY join DEPARTMENTS using (department_id) 
JOIN LOCATIONS USING (location_id)
where JOB_ID != 'SA_REP';


---Question 8
SELECT DISTINCT JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE HIRE_DATE < '&specific_date'
ORDER BY DEPARTMENT_ID DESC, JOB_ID ASC;

---Question 9
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(E.SALARY) FROM EMPLOYEES E JOIN EMPLOYEES M ON(E.MANAGER_ID=M.EMPLOYEE_ID)
                WHERE E.SALARY>M.SALARY );
                      
---Question 10
SELECT DEPARTMENT_ID "Department Number", DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) "The Number of Employees"
FROM EMPLOYEES E JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_ID,DEPARTMENT_NAME
HAVING COUNT(EMPLOYEE_ID)= (SELECT MAX(COUNT(EMPLOYEE_ID))FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

---Question 11
SELECT LAST_NAME||', '||FIRST_NAME "NAME", HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE>(SELECT HIRE_DATE FROM EMPLOYEES WHERE FIRST_NAME='Bruce' AND LAST_NAME='Ernst');

---Question 12
SELECT LAST_NAME, DEPARTMENT_ID "Department Number", JOB_ID
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
     JOIN LOCATIONS USING (LOCATION_ID)
WHERE LOCATION_ID='&Specific_location_id';
